steps:
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - docker login ${_ACR_URL} -u ${_ACR_USERNAME} -p ${_ACR_PASSWORD}
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--build-arg'
      - TAG_NAME=$SHORT_SHA
      - '-t'
      - bizifyprod.azurecr.io/payroll-fronend:$SHORT_SHA
      - '-f'
      - Dockerfile
      - .
  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - '-c'
      - docker push bizifyprod.azurecr.io/payroll-fronend:$SHORT_SHA
  - name: gcr.io/cloud-builders/curl
    entrypoint: curl
    args:
      - '--header'
      - 'x-organization-id: e3d19597-2a4f-46a9-b3be-bfd0da5c1792'
      - '--header'
      - 'x-project-id: 8abc77d2-d0ba-4804-873c-c94236f38d4b'
      - '-d'
      - '{ "channel": "default",  "update_type": "patch", "container_id": "16f62d1d-ea5b-400e-ac86-b4003e892bdc",  "image_name_with_tag": "bizifyprod.azurecr.io/payroll-fronend:$SHORT_SHA"}'
      - '-X'
      - POST
      - https://beta.api.platformer.com/rudder/webhook/v1/container?token=${_PLATFORMER_AUTOGENERATED_CICD}
